### ISSUE TITLE
Allow apache to run with any user ID

### ISSUE THREAD

**Issue by michelesr** [kobe25/osm-tiles#5]
This happens when running with a different uid:

``` [log_config:error] [pid 9:tid 139717476407168] (13)Permission denied: AH00649: could not open transfer log file /var/log/apache2/other_vhosts_access.log.```

**Comment by kobe25** [comment]
I think we can address this simply changing `APACHE_LOG_DIR` to `/tmp` in the Dockerfile.  And it should be also necessary changing other envvars.

But..  I suppose before doing that, we should remove Supervisor and split into two different containers.
